name: brandtech_shop
description: "BrandTECH Product Listing App — Flutter Technical Task"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Navigation
  go_router: ^17.2.3

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  dio: ^5.9.2
  connectivity_plus: ^7.1.1

  # UI
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  google_fonts: ^8.1.0


  # Utils
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  equatable: ^2.0.8
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.4-dev.1


flutter:

  uses-material-design: true

  assets:
    - assets/


